Css brochure form
Matthew-Abebe/c0321-code-solutions pull request #18
Opened 2021-03-12 05:15 UTC by Matthew-Abebe

![Screenshot (74)](https://user-images.githubusercontent.com/44979851/110895565-e0a8a080-82ae-11eb-8464-6dbfd267a377.png)

2021-03-12 19:42 UTC, codingcodymiller requested changes
Hey matt! Your label font size is a bit large, and they are no indented at all, please revise and show me an updated screenshot, and I will take a look again 👍

2021-03-12 20:11 UTC, Matthew-Abebe commented
![Screenshot (82)](https://user-images.githubusercontent.com/44979851/110993317-01fba200-832c-11eb-8a74-1acbea29d314.png)

2021-03-13 00:19 UTC, codingcodymiller requested changes
Great work!! One minor change:

2021-03-13 00:19 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  margin-left: 325px;
Woah, big movement! Instead of doing this, try putting the button in a `div`, and apply `text-align: right`

2021-03-13 00:44 UTC, Matthew-Abebe commented on css-brochure-form/styles.css
> +  margin-left: 325px;
The button was already in a div. I removed the margin-left property and added a text-align property to the css rule with a value of right, but the button shifted to the left. Should the div have an id to target so that the styling can apply? I am using button as a selector as of now.

2021-03-13 01:35 UTC, Matthew-Abebe commented
![Screenshot (86)](https://user-images.githubusercontent.com/44979851/111014613-62ed9f00-8359-11eb-9658-9095a1b63451.png)

2021-03-15 17:32 UTC, codingcodymiller approved these changes
Nice work!!

2021-03-15 17:51 UTC, merged