Completed css-positioning
Matthew-Abebe/c0321-code-solutions pull request #19
Opened 2021-03-12 20:01 UTC by Matthew-Abebe

![Screenshot (78)](https://user-images.githubusercontent.com/44979851/110992139-60c01c00-832a-11eb-9963-0dbb58f2431e.png)
![Screenshot (81)](https://user-images.githubusercontent.com/44979851/110992216-79303680-832a-11eb-8536-68dcb1666d64.png)
![Screenshot (80)](https://user-images.githubusercontent.com/44979851/110992235-7e8d8100-832a-11eb-933f-db9dcd79348f.png)

2021-03-12 20:45 UTC, codingcodymiller requested changes

2021-03-12 20:45 UTC, codingcodymiller commented on css-positioning/absolute.css
> +  bottom: 225px;
These are large movements. Since the emoji rests against the top right corner, you will want to use the `top` and `right` box offset properties.

2021-03-12 20:45 UTC, codingcodymiller commented on css-positioning/absolute.css
> +  top: 160px;
Same issue here. The joke rests against the bottom, so you'll want to use the `bottom` box offset property

2021-03-12 22:57 UTC, Matthew-Abebe commented on css-positioning/absolute.css
> +  top: 160px;
![Screenshot (84)](https://user-images.githubusercontent.com/44979851/111007249-4181b880-8343-11eb-8abc-3add9c6ad47f.png)

2021-03-13 00:15 UTC, codingcodymiller approved these changes

2021-03-13 00:36 UTC, merged