Completed javascript-local-storage.
Matthew-Abebe/c0321-code-solutions pull request #46
Opened 2021-03-27 00:07 UTC by Matthew-Abebe

![Screenshot (199)](https://user-images.githubusercontent.com/44979851/112703862-b2ea5c80-8e55-11eb-9877-3cf3221f0246.png)

2021-03-27 00:22 UTC, codingcodymiller requested changes

2021-03-27 00:22 UTC, codingcodymiller commented on javascript-local-storage/data.js
> +todos = JSON.parse(previousTodosJSON);
You should check if there is anything stored in `previousTodosJSON` before reassigning the value of `todos`. If there isn't anything there, the value will be `null`, which means you would be destroying the array.

2021-03-30 04:34 UTC, Matthew-Abebe commented on javascript-local-storage/data.js
> +todos = JSON.parse(previousTodosJSON);
![Screenshot (240)](https://user-images.githubusercontent.com/44979851/112934387-85601600-90d6-11eb-9bc2-f0908570833b.png)

2021-03-30 17:40 UTC, codingcodymiller approved these changes

2021-03-31 02:02 UTC, merged