Javascript loops practice
Matthew-Abebe/c0321-code-solutions pull request #48
Opened 2021-03-27 16:27 UTC by Matthew-Abebe

![Screenshot (203)](https://user-images.githubusercontent.com/44979851/112727224-b0801500-8ede-11eb-9874-4c88a3b62c5a.png)
![Screenshot (204)](https://user-images.githubusercontent.com/44979851/112727226-b4ac3280-8ede-11eb-90d5-30ee68e4b2a7.png)

2021-03-29 19:29 UTC, codingcodymiller requested changes
Great start here!! Please see my notes. Also, you seem to have the files for `string-manipulation-1` included in this accidentally, please delete that directory before you commit your changes for this branch.

2021-03-29 19:29 UTC, codingcodymiller commented on javascript-loops-practice/add-suffix-to-all.js
> +    words[i] += suffix;
In general, functions should not affect the original array or object they are using. Rather than changing the original value here, you should make a new array, and add the adjusted data to that array, then return that array

2021-03-29 19:29 UTC, codingcodymiller commented on javascript-loops-practice/get-indexes.js
> +    var index = array.indexOf(array[i]);
Why not just use `i`?

2021-03-29 19:29 UTC, codingcodymiller commented on javascript-loops-practice/includes-seven.js
> +      hasSeven = true;
This will only work if the last number is `7`. Try changing this line to just `return true`

2021-03-29 19:29 UTC, codingcodymiller commented on javascript-loops-practice/includes-seven.js
> +  return hasSeven;
Make this `return false`

2021-03-30 04:29 UTC, Matthew-Abebe commented on javascript-loops-practice/includes-seven.js
> +  return hasSeven;
![Screenshot (238)](https://user-images.githubusercontent.com/44979851/112934064-d1f72180-90d5-11eb-9749-3a1579536fd6.png)
![Screenshot (239)](https://user-images.githubusercontent.com/44979851/112934077-d7ed0280-90d5-11eb-80a6-e596870e802b.png)

2021-03-30 17:42 UTC, codingcodymiller requested changes

2021-03-30 17:42 UTC, codingcodymiller commented on javascript-loops-practice/add-suffix-to-all.js
> +    newArr.push(words[i] += suffix);
You are still affecting the original array by using `+=`. You should change it to just `+`

2021-04-05 17:24 UTC, codingcodymiller approved these changes

2021-04-05 17:46 UTC, merged