String manipulation 1
Matthew-Abebe/c0321-code-solutions pull request #49
Opened 2021-03-27 19:27 UTC by Matthew-Abebe

![Screenshot (212)](https://user-images.githubusercontent.com/44979851/112732526-bafad880-8ef7-11eb-9201-a6da84fc601f.png)
![Screenshot (213)](https://user-images.githubusercontent.com/44979851/112732529-bf26f600-8ef7-11eb-8ece-60fc7b218da6.png)

2021-03-29 19:51 UTC, codingcodymiller requested changes
Great start here! Please see my notes

2021-03-29 19:51 UTC, codingcodymiller commented on string-manipulation-1/src/get-words.js
> +    var word = string.split(' ');
The `split` method already uses a loop for you, this loop is unnecessary. I recommend you tinker with `split` and see what steps are actually necessary here.

2021-03-29 19:51 UTC, codingcodymiller commented on string-manipulation-1/src/is-vowel.js
> +  if (char === 'A' || char === 'E' || char === 'I' || char === 'O' || char === 'U' || char === 'a' || char === 'e' || char === 'i' || char === 'o' || char === 'u') {
If you convert the letter to either `upperCase` or `lowerCase`, this condition can be reduced by half.

2021-03-30 04:14 UTC, Matthew-Abebe commented on string-manipulation-1/src/is-vowel.js
> +  if (char === 'A' || char === 'E' || char === 'I' || char === 'O' || char === 'U' || char === 'a' || char === 'e' || char === 'i' || char === 'o' || char === 'u') {
![Screenshot (234)](https://user-images.githubusercontent.com/44979851/112932922-aa06be80-90d3-11eb-8296-c32980d893f9.png)
![Screenshot (235)](https://user-images.githubusercontent.com/44979851/112932940-b1c66300-90d3-11eb-8f97-d03cebd4487d.png)

2021-04-05 17:24 UTC, codingcodymiller approved these changes

2021-04-05 17:46 UTC, merged