Array manipulation 1
Matthew-Abebe/c0321-code-solutions pull request #52
Opened 2021-04-05 22:56 UTC by Matthew-Abebe

![Screenshot (319)](https://user-images.githubusercontent.com/44979851/113636419-5e9a6600-9627-11eb-803c-0eca2d940316.png)
![Screenshot (320)](https://user-images.githubusercontent.com/44979851/113636431-62c68380-9627-11eb-8771-eb3ca44a36d9.png)

2021-04-06 16:43 UTC, codingcodymiller requested changes

2021-04-06 16:43 UTC, codingcodymiller commented on array-manipulation-1/src/reverse.js
> +  return (newArr);
You don't need to be putting parentheses around your returns like this. You should remove them.

2021-04-06 16:43 UTC, codingcodymiller commented on array-manipulation-1/src/tail.js
> +  return (newArr);
You don't need to be putting parentheses around your returns like this. You should remove them.

2021-04-06 16:43 UTC, codingcodymiller commented on array-manipulation-1/src/last.js
> +  return (array[array.length - 1]);
You don't need to be putting parentheses around your returns like this. You should remove them.

2021-04-06 16:43 UTC, codingcodymiller commented on array-manipulation-1/src/initial.js
> +  return (newArr);
You don't need to be putting parentheses around your returns like this. You should remove them.

2021-04-06 16:43 UTC, codingcodymiller commented on array-manipulation-1/src/compact.js
> +  return (newArr);
You don't need to be putting parentheses around your returns like this. You should remove them.

2021-04-06 19:31 UTC, Matthew-Abebe commented
![Screenshot (327)](https://user-images.githubusercontent.com/44979851/113767839-00778c80-96d4-11eb-8b81-0b3f76280280.png)
![Screenshot (328)](https://user-images.githubusercontent.com/44979851/113767853-03727d00-96d4-11eb-951e-19cadb9e9aca.png)

2021-04-07 17:11 UTC, scbowler approved these changes
Looks good 👍 

One FYI comment below for `compact`, no change required

2021-04-07 17:11 UTC, scbowler commented on array-manipulation-1/src/compact.js
> +    if (array[i] !== false && array[i] !== 0 && typeof array[i] !== 'undefined' && array[i] !== '' && array[i] !== null && !Number.isNaN(array[i])
There is probably an easier way to check if something is falsy... 🤔

2021-04-07 19:46 UTC, merged