Completed html-forms.
Matthew-Abebe/c0321-code-solutions pull request #7
Opened 2021-03-09 23:22 UTC by Matthew-Abebe

![Screenshot (49)](https://user-images.githubusercontent.com/44979851/110551878-36345000-80eb-11eb-90c9-9be5d320ca46.png)

2021-03-09 23:35 UTC, codingcodymiller requested changes
Great work so far!! Please see my notes

2021-03-09 23:35 UTC, codingcodymiller commented on html-forms/index.html
> +      <div>Email</div>
This should be a `label` element. Make sure you use a `for` attribute with a value that matches the `id` of the form control element this is labelling!

Also, the `input` should be a sibling to the `label`, not a child of it.

2021-03-09 23:35 UTC, codingcodymiller commented on html-forms/index.html
> +    <form>
All of the form control elements in this exercise should be in one form, please remove the extra forms in your code.

2021-03-09 23:35 UTC, codingcodymiller commented on html-forms/index.html
> +        <select id="codingCool">
The `select` should be a sibling to the `label`, not a child of it.

2021-03-09 23:35 UTC, codingcodymiller commented on html-forms/index.html
> +        <input type="radio" name="favoriteLanguage" value="JavaScript">JavaScript
The text for each option should be in a `label` element. Make sure you use a `for` attribute with a value that matches the `id` of the form control element this is labelling!

2021-03-09 23:35 UTC, codingcodymiller commented on html-forms/index.html
> +    <div>Comments</div>
This should be a `label` element. Make sure you use a `for` attribute with a value that matches the `id` of the form control element this is labelling!

2021-03-09 23:35 UTC, codingcodymiller commented on html-forms/index.html
> +      <label for="comments">
This `label` can be removed.

2021-03-09 23:59 UTC, Matthew-Abebe commented on html-forms/index.html
> +      <label for="comments">
Are you sure? The example shows a label above the text area that says 'comments'.

2021-03-10 00:07 UTC, Matthew-Abebe commented on html-forms/index.html
> +      <label for="comments">
I think I figured it out.

2021-03-10 00:10 UTC, Matthew-Abebe commented on html-forms/index.html
> +        <input type="radio" name="favoriteLanguage" value="JavaScript">JavaScript
When I use Id instead of name for the radio buttons it does not let me de-select an option. Is using name as an attribute appropriate here?

2021-03-10 00:12 UTC, Matthew-Abebe commented
![Screenshot (51)](https://user-images.githubusercontent.com/44979851/110555850-3126cf00-80f2-11eb-96e9-df5035063ddd.png)

2021-03-10 01:12 UTC, codingcodymiller requested changes
Nice improvement! A couple more notes:

2021-03-10 01:12 UTC, codingcodymiller commented on html-forms/index.html
> +        <input type="radio" name="favoriteLanguage" value="JavaScript">
Please revise this portion per our discussion in Q&A. Each radio input should have its own id and a label that correlates to that id

2021-03-10 01:12 UTC, codingcodymiller commented on html-forms/index.html
>          <textarea name="comments" cols="20" rows="4"></textarea>
You want an `id` on this element to match the `for` attribute on its label

2021-03-10 01:41 UTC, codingcodymiller approved these changes

2021-03-10 01:41 UTC, merged